-- FetchPedidoByNumero
SELECT 
PEDIDOS.ABREV,
PEDIDOS.NUMPEDIDO,
PEDIDOS.VALORTOTAL,
PEDIDOS.NUMEROCLI,
CONDPAG.DESCRICAO AS "CONDICAO",
CLIENTES.RAZSOC AS "CLIENTE.RAZSOC"
FROM PEDIDOS 
INNER JOIN CLIENTES 
ON PEDIDOS.NUMEROCLI = CLIENTES.NUMERO 
INNER JOIN CONDPAG
ON PEDIDOS.CODCONDPAG = CONDPAG.CODIGO
WHERE PEDIDOS.NUMPEDIDO = :numero

-- FetchPedidoByCliente
SELECT 
PEDIDOS.ABREV,
PEDIDOS.NUMPEDIDO,
PEDIDOS.VALORTOTAL,
PEDIDOS.NUMEROCLI,
PEDIDOS.DATAEMISSAO AS "DATA",
CONDPAG.DESCRICAO AS "CONDICAO",
VENDED.NOME AS "VENDEDOR",
CLIENTES.RAZSOC AS "CLIENTE.RAZSOC"
FROM PEDIDOS 
INNER JOIN CLIENTES 
ON PEDIDOS.NUMEROCLI = CLIENTES.NUMERO 
INNER JOIN CONDPAG
ON PEDIDOS.CODCONDPAG = CONDPAG.CODIGO
INNER JOIN VENDED
ON PEDIDOS.CODVENDEDOR = VENDED.COD
WHERE PEDIDOS.NUMEROCLI = :cnpj

-- FetchProdutosFromPedidoByNumero
SELECT 
CODPRODUTO,
QUANTIDADE,
PRECOUNIT,
PORCEDESCONTO,
VALORTOTAL
FROM ITENSPE
WHERE NUMPEDIDO = :numero

-- FetchProdutoByCodigo
SELECT 
ABREV,
CODIGO,
DESCRICAO,
COMPLEMENTO,
UNIMED,
CLASFISCAL,
GRUPOS
FROM PRODUTOS
WHERE CODIGO = :codigo

-- FetchClienteByCnpj
SELECT 
NUMERO,
RAZSOC,
NOMFANT,
ENDERECO,
COMPLEMENTO,
BAIRRO,
CID,
CEP,
EST,
TEL,
OBS,
EMAIL
FROM CLIENTES
WHERE NUMERO = :cnpj

-- FetchTransportadoraByCodigo
SELECT 
CODIGO,
NOME,
NOMFANT,
NUMERO,
INSCREST,
FONE,
ENDERECO,
BAIRRO,
CIDADE,
ESTADO,
CEP
FROM TRANSPO
WHERE CODIGO = :codigo

-- FetchCondicaoByDescricao
SELECT 
CODIGO,
DESCRICAO
FROM CONDPAG
WHERE DESCRICAO = :descricao

