-- FetchPedidoByNumero
SELECT 
PEDIDOS.ABREV,
PEDIDOS.NUMPEDIDO,
PEDIDOS.VALORTOTAL,
PEDIDOS.NUMEROCLI,
PEDIDOS.DATAEMISSAO AS "DATA",
CLIENTES.RAZSOC AS "CLIENTE.RAZSOC",
CLIENTES.CID AS "CLIENTE.CIDADE",
CLIENTES.EST as "CLIENTE.UF",
CONDPAG.DESCRICAO AS "CONDICAO",
ITENSPE.CODPRODUTO AS "ITEM.CODIGO",
ITENSPE.QUANTIDADE AS "ITEM.QUANTIDADE",
ITENSPE.PRECOUNIT AS "ITEM.PRECO",
ITENSPE.LOCALIZACAO AS "ITEM.LOCAL"
FROM PEDIDOS 
INNER JOIN CLIENTES 
ON PEDIDOS.NUMEROCLI = CLIENTES.NUMERO 
INNER JOIN CONDPAG
ON PEDIDOS.CODCONDPAG = CONDPAG.CODIGO
INNER JOIN ITENSPE
ON PEDIDOS.NUMPEDIDO = ITENSPE.NUMPEDIDO

-- FetchReciboByNumero
SELECT
RECIBOS.NUMNOTA,
RECIBOS.NUMEROCLI,
RECIBOS.VALTOTAL,
RECIBOS.DTEMISSAO AS "DATA",
CLIENTES.RAZSOC AS "CLIENTE.RAZSOC",
CLIENTES.CID AS "CLIENTE.CIDADE",
CLIENTES.EST as "CLIENTE.UF",
CONDPAG.DESCRICAO AS "CONDICAO"
FROM NFMODEL1 RECIBOS
INNER JOIN CLIENTES 
ON RECIBOS.NUMEROCLI = CLIENTES.NUMERO 
INNER JOIN CONDPAG
ON RECIBOS.CODCONDPAG = CONDPAG.CODIGO

-- FetchProdutosFromPedidoByNumero
SELECT 
CODPRODUTO,
QUANTIDADE,
PRECOUNIT,
PORCEDESCONTO,
VALORTOTAL
FROM ITENSPE
WHERE NUMPEDIDO = :numero

-- FetchProdutoByCodigo
SELECT 
ABREV,
CODIGO,
DESCRICAO,
COMPLEMENTO,
UNIMED,
CLASFISCAL,
GRUPOS
FROM PRODUTOS
WHERE CODIGO = :codigo

-- FetchClienteByCnpj
SELECT 
NUMERO,
RAZSOC,
NOMFANT,
ENDERECO,
COMPLEMENTO,
BAIRRO,
CID,
CEP,
EST,
TEL,
OBS,
EMAIL
FROM CLIENTES
WHERE NUMERO = :cnpj

-- FetchClienteByNome
SELECT 
NUMERO,
RAZSOC,
NOMFANT,
ENDERECO,
COMPLEMENTO,
BAIRRO,
CID,
CEP,
EST,
TEL,
OBS,
EMAIL
FROM CLIENTES

-- FetchTransportadoraByCodigo
SELECT 
CODIGO,
NOME,
NOMFANT,
NUMERO,
INSCREST,
FONE,
ENDERECO,
BAIRRO,
CIDADE,
ESTADO,
CEP
FROM TRANSPO
WHERE CODIGO = :codigo

-- FetchCondicaoByDescricao
SELECT 
CODIGO,
DESCRICAO
FROM CONDPAG
WHERE DESCRICAO = :descricao

-- FetchVendedorByNome
SELECT 
COD,
ABREV,
NOME,
FONE,
EMAIL
FROM VENDED
WHERE NOME = :nome


