-- FetchPedidoByNumero
SELECT 
P.ABREV,
P.NUMPEDIDO,
P.VALORTOTAL,
P.NUMEROCLI,
C.RAZSOC AS "CLIENTE.RAZSOC"
FROM PEDIDOS P
INNER JOIN CLIENTES C
ON P.NUMEROCLI = C.NUMERO 
WHERE P.NUMPEDIDO = :numero

-- FetchPedidoByCliente
SELECT 
PEDIDOS.ABREV,
PEDIDOS.NUMPEDIDO,
PEDIDOS.VALORTOTAL,
PEDIDOS.NUMEROCLI,
CLIENTES.RAZSOC
FROM PEDIDOS 
INNER JOIN CLIENTES 
ON PEDIDOS.NUMEROCLI = CLIENTES.NUMERO 
WHERE PEDIDOS.NUMEROCLI = :cnpj

-- FetchProdutosFromPedidoByNumero
SELECT 
CODPRODUTO,
QUANTIDADE,
PRECOUNIT,
PORCEDESCONTO,
VALORTOTAL
FROM ITENSPE
WHERE NUMPEDIDO = :numero

